name: Test Workflow

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Say Hello
      run: echo "GitHub Actions setup successful!"
